# Generated by Django 5.0.4 on 2024-12-10 11:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(choices=[('townhouse', 'Town House'), ('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('studio', 'Studio')], default='house', max_length=30)),
                ('status', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='sale', max_length=15)),
                ('units_available', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bedrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('square_feet', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('views', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('landlord', models.ForeignKey(editable=False, limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
